- name: configuration catalogue  server
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs
    command: dnf module enable nodejs:20 -y
  - name: install nodejs
    package:
      name: nodejs
      state: present
  - name: create roboShop system user
    user:
      name: roboShop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "RoboShop system user"    

